services:
  - type: web
    name: my-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    environment:
      pythonVersion: 3.11.9
    runtime: python-3.11
