services:
  - type: web
    name: my-app          # можно заменить на название твоего проекта
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
