services:
  - type: web
    name: trading-bot
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python main.py
    environment:
      pythonVersion: 3.11.9
    runtime: python-3.11
